name = "xiaoxin-mail-api"
main = "src/index.js"
compatibility_date = "2023-11-10"

# 发布到Workers.dev子域
workers_dev = true

# 变量绑定
[vars]
ENVIRONMENT = "production"
APP_NAME = "小新邮箱"
JWT_SECRET_KEY = "dev_secret_key_change_in_production"

# R2存储桶绑定
[[r2_buckets]]
binding = "MAIL_BUCKET"
bucket_name = "xiaoxin-mail-content"
preview_bucket_name = "xiaoxin-mail-content-dev" # 可选，开发环境使用

# KV命名空间绑定
[[kv_namespaces]]
binding = "MAIL_KV"
id = "YOUR_KV_NAMESPACE_ID" # 替换为实际KV命名空间ID
preview_id = "YOUR_KV_PREVIEW_NAMESPACE_ID" # 替换为实际开发环境KV命名空间ID

# D1数据库绑定
[[d1_databases]]
binding = "MAIL_DB"
database_name = "xiaoxin-mail-db"
database_id = "YOUR_D1_DATABASE_ID" # 替换为实际D1数据库ID

# 环境变量绑定 - 生产环境
[env.production]
name = "xiaoxin-mail-api"
vars = { ENVIRONMENT = "production" }

# 环境变量绑定 - 测试环境
[env.staging]
name = "xiaoxin-mail-api-staging"
vars = { ENVIRONMENT = "staging" }

# 开发环境配置
[env.development]
name = "xiaoxin-mail-api-dev"
vars = { ENVIRONMENT = "development" } 